### ISSUE TITLE
stacks-blockchain-api fails to start because of BNS_IMPORT_DIR

### ISSUE THREAD

**Issue by codexbtc** [stacksfoundation/stacks-machine-images#4]
Once the node is deplyed, it fails to start due to the var `BNS_IMPORT_DIR` in .env file. Leaving it commented by default fixes the problem.

**Comment by wileyj** [comment]
got it, thanks!

**Comment by wileyj** [comment]
there is a sed in the machine build process here: https://github.com/stacksfoundation/stacks-machine-images/blob/master/scripts/02-stacks-blockchain.sh#L10-L11

that either needs to be removed, or the BNS import files need to pulled into the image as it's built. 
@codexbtc  - do you have any files on your droplet in the dir `/opt/stacks-blockchain-docker/persistent-data/bns-data`?

i.e.
```
$ ls -al persistent-data/bns-data/
total 1123864
drwxr-xr-x 2 root  root         4096 Mar 11 01:59 .
drwxr-xr-x 4 admin admin        4096 Mar 31 04:06 ..
-rw-r--r-- 1   501 dialout  17476569 Jan 13  2021 chainstate.txt
-rw-r--r-- 1   501 dialout        64 Jan 13  2021 chainstate.txt.sha256
-rw-r--r-- 1 root  root    303673370 Mar 11 01:48 export-data.tar.gz
-rw-r--r-- 1   501 dialout    349655 Jan 13  2021 name_zonefiles.txt
-rw-r--r-- 1   501 dialout        64 Jan 13  2021 name_zonefiles.txt.sha256
-rw-r--r-- 1   501 dialout 427583709 Mar 19  2021 subdomains.csv
-rw-r--r-- 1   501 dialout        64 Mar 19  2021 subdomains.csv.sha256
-rw-r--r-- 1   501 dialout 401714135 Jan 13  2021 subdomain_zonefiles.txt
-rw-r--r-- 1   501 dialout        64 Jan 13  2021 subdomain_zonefiles.txt.sha256
```

**Comment by wileyj** [comment]
Thanks!
this commit (untested at the moment) should resolve it: https://github.com/stacksfoundation/stacks-machine-images/commit/fdc1b377d83e02ceb89c75400bdb0d5d0079d88f

essentially, disable the BNS env var uncomment command, and add some docs on how to enable some extra flags
